version: "3.3"
services:
  webserver:
    container_name: webserver
    build:
      context: . # Context adalah directory tempat Dockerfile berada
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html/ # Mapping folder local ke dalam container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mapping konfigurasi Nginx
    ports:
      - 80:80
      - 443:443
  database:
    container_name: database
    image: mysql:8.0 # Pastikan menggunakan versi MySQL yang sesuai
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arista1234
      MYSQL_DATABASE: arista
      MYSQL_USER: arista
      MYSQL_PASSWORD: arista123
    ports:
      - 9906:3306
    volumes:
      - ./dbdata:/var/lib/mysql
