version: "3.8"
services:
  webserver:
    container_name: webserver
    build:
      context: . # Context adalah directory tempat Dockerfile berada
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html # Mapping folder local ke dalam container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mapping konfigurasi Nginx
    ports:
      - "8080:80" # Akses HTTP melalui port 8080
      - "443:443" # Akses HTTPS (pastikan sertifikat SSL tersedia)
    environment:
      - TZ=Asia/Jakarta # Sesuaikan dengan timezone Anda
  database:
    container_name: database
    image: mysql:8.0 # Pastikan menggunakan versi MySQL yang sesuai
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strongRootPass1234
      MYSQL_DATABASE: arista
      MYSQL_USER: arista
      MYSQL_PASSWORD: strongUserPass123
      TZ: Asia/Jakarta # Sesuaikan dengan timezone Anda
    ports:
      - "9906:3306" # Port untuk akses MySQL
    volumes:
      - ./dbdata:/var/lib/mysql # Mapping data MySQL
